env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - secure: rQmMfl4LMSnMpsiSR1j7E/ZyTtg9ceFjJZV82ySFQpD0qKqajDTIpXyM/JlADhL7CUL5BQZGlZHk26VRgu3D91W+XbElt01TvbNAlCts3rCsDDeEcWX4SZWiwpFZqemgBP414YxoZKm4bHPMGEMDnsWaNKnqWo5JKApyFj5GswyFbJUe6I2xi41poyedkRN/Q2PNKFFYz3c485aP93m/XE/LveNNKFodOavPRMnmQ5dPOvwQnMrGchESAIKzsvPfHssMV2tbvCl376al5a49SOBJKktrF0ITjegq/Rp7VAsP2VPNABHutYgnyPAAlf7sKvA0C0MRdaSLrQLcwgQ4ny1pYKePloQLrSNjRXpIiO7VYqX5unsB+ikbHHxXewirNWk81gKVLnm1uDSlhqDB+9Lkp3Tf2ABh2Ftgx3DsU+31zxtrQfyM/CICSH+3UevAjQgRytcDmYCiB1eG6azthzz9zkHPc/Z5L9Tb3KtpXTCTPAVl5aNBq63pFonsB2fgkBlj9pG3/CYOaCQG6nmDUIkVu+CDymSzlgYP52+6HvG2bjLCrRpEpCX/UmvDIi/B03beeMBsD2ysoE81/cAPOpDtBEGySLCSF/UwNoYuUvdDZGgXv+mrsEEME9E9ceEBR18Ts8B+EITiABrPXRLdk8cfWTCUNil4HBTv89KaVt4=
  - secure: CcbRtmkF2yvwvOM/sB5D1K+brcCfNqwoX0twIum0W/T1E6yEpd8PUza7bKiJwPWDQDMUfr9o4VtA5gRRKvldZkY19aqQ1gg2/cYZZq3lLhmsw152OOfMelfZBNAt3fHeN9bCUxzw4dimjaiIzDK5K3RTleSuQiQzRANxcLNlnvfrkPu3ZGw9tBzWb4GhAW5NWn/g7Wcvj/5VU3DcYTp9nA9tdKQCKEm83Pex7NG59R1QKfwWGVVfAIhGVmvv2P/Rz0bY1wxeJffzZKkJECE2nCg4vdi9xoySn786HfN9KuIMA22ZLknUMCCJ0Nfs/i/dWC97RLevbOi8mSIgXqQtfkslmV7q+CuOpyYwOsoZ3XXnBBVoBLYfvXSgEvF+6mWgtvTAVXk3jr92Okdu6bx4RTHTh2WNL4FfJp75/Lt29P1vrJ6poqjihTVIfsmwLKgYfrUvlb9FBgLnhSHqz3RD6g2AYrn2hzljdoNSYSnScbS21FCAWmDf5Kybaxv4WF/qONpOzGM3r3royO5R1dF9DorJZIqDRFQ5QFhaV5410fLAxnUQVaOmQY5slnKSiz656cY5RPfkYqd8UYQfroXzJ9QQ7YrvjZRybyPbBgiNgx3GUZNx/CN+p/ufDTBNRU9JWoNYs/cXv2vk/LNCsHDKs/E7N+RnIk5qOsmSVHyiOD4=
  - secure: MLkonoZOEydhdM+E4LTh5Vk82dtgXnytmzDHwX3vdoGlT8q1pLO5f8aUFwO11jUv37fuoLV7McqlpA4IZtd6pXwsTZTCKZPua1f9Go5iUA3hVqm77fE0n2HRcQQKru4EVv4WIjjjmFna4zrOpW3XCWicFOnKPguSGYOa28Dax6u+b3NyRhs0+ajNC3ult+rUdmMIgPJh7mgTqVyVUAsT8h/LnMhRcy+SZK9Th9KG92URqaGQXH0jERjWpBvfKd8UNzB7+0cpUY1ZmQ1Q13HHe1VIHBrLG9V71gTRCFgWu8DJSK89hUbRD/nWVcIuRLDWGm6grmTPkUXppvc5EacflC/PWvEYKXz+cMtsA9YuTe+YsNVexP5SCULBwVgOhJDlpCSugy/EJXDyuqxD7ioF/9eJDaHkZUcxiiWJzhGkEFla6hSwHU5+jd/LaLOa0I//fFsjY/Cw0q7KXYL1OnEEuGGLFo07moa8KKkhdmzYAZg3s4jP4NrL/DkFA82XufHYWZplPvVdHiHslVn8fBbZ9mqe4QcwpU9ezaYD2I/g5MpX/EGiCR/5j5yWoSKGumujFgdl8Sk+IRY1rJ1uxz+3tW9SM89RH7MwtpeTyC4w5eF0rMZItUpoUw6tZGvg1Y702+MVN1iRAM6hSVORMgMo9YgyZnrTjYqgGlgHa2+1jxU=
  - secure: tt4JBwzWomKsDPo+UfO2OAMyt6nNM7Ryq4OTN/jYzw6nk8QmNXI1d/Rlrg24eFBInrV5Ror+o9roxV/Zl7W9IG4vy6E+sODzZvw4YTL7LjefVZqME8R4qlNE/eel5ZgpOqx965tQDju+gnwpATRuBi5qa08D5pg+rjpM38K/LL7Zoy3WLlh0frjEy5MOQzeD6qWNErEwrwDubHccmZ8qbHQ7hSswtxyruOPOz52Dw/0VmIWpEnfnupOOvAEvERW11GGsBJVV1DJ9evA8wBoOADchZuhFVpjzAzh+2FxB8jXjKMCaJ8j8gy9UoliaSP6hKjGcSJJyBp6KogdBIaLQEg8cu6gnmgdy3WU/W9UYySSUt1LHngmMxdEYfvOzF2ewQM1trttWbRNc4zv85kJ/uuXETxtfJ0MFcJH21wd7VHPBResDJEPJ9qDRCx45IV1/3J6/Mp0sBc2h5BujacWeucro98jKLFh8E4lphNye9S78hJej4ObGGjmK+AkGq0ubRVgOKa8tWDmE+BML7Xq00QUArvqQBXV+DbYjPar/5DWgyZrk2kjJoc/gTpiHhyJUrZ5q5A+y8kqaRs+eMD9FKiJS4M8Ed0jQFwGBScuRTJ1qf+1M3EK7pQkyVYdJldTbtj+t5OhJ0BldvQDqa8z2HbVvzCSULqvhfGXjEXy6VCw=

addons:
  apt:
    packages:
      - sshpass

branches:
  only:
  - Production
  - Development

sudo: required

before_install:
- sudo chmod +x tests.sh

script: "./tests.sh"

after_success:
  - mkdir build
  - mv * build
  - tar -czf package.tgz build
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o stricthostkeychecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
