sudo: required

before_install:
- sudo add-apt-repository -y ppa:webupd8team/java
- sudo apt-get update
- sudo apt-get install -y \
  oracle-java8-installer \
  maven
- sudo apt-get -f install
- sudo apt-get autoremove
- sudo apt-get -y autoclean
- sudo apt-get -y clean

script: "./test.sh"